services:

  mysql:
    image: mysql:8.0
    container_name: ai-rti-mysql

    environment:
      MYSQL_DATABASE: ai_rti_assistant
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ai-rti-backend

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_rti_assistant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    restart: unless-stopped


volumes:
  mysql-data: